name: Create the files.

on:
  workflow_dispatch:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      
      - name: delete non release
        if: ${{ github.event.inputs.create_release == true }}
        run: rm .github-new/ci.yml

      - name: delete release
        if: ${{ github.event.inputs.create_release == false }}
        run: |
          rm .github-new/ci-release.yml

      - name: move the files
        run: |
          rm -r .github
          mv .github-new .github
      
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added scaffolding and readme."
          git push
