name: Create the files.

on:
  workflow_dispatch:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      
      - name: move the files
        run: mv workflows /.github/
      
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added scaffolding and readme."
          git push
